### PR TITLE
Duplicate loaders should be reduced to 1 loader if the version range of each is compatible

### PR DESCRIPTION
**Pull request by edeustace**
having duplicate loaders results in a webpack error. if the version range is compatible then use the latest version and conflate. if the version range isn't compatible throw an error.

### CODE REVIEW

**Comment by rbokel** [comment]
The problem occurs, when a loader is applied twice. This only happens when the filename passes the test regexp on both loader definitions. When the regexps are different, we don't have a problem. 
However, regexps can look very different but match the same things. I'm not sure, if there is a solution for this.

**Comment by edeustace** [comment]
On reflection I don't think this is a bug, more of a lack of documentation and some missing validation of user input. The documentation should be updated to explain that there are 2 frameworks already supported: `react` and `less: require('style!css!less')`.

So there is no need to add either of these to a support module.

Also we should check the webpack config for duplicate loaders and Error appropriately instead of sending it on to webpack and letting it fail there.

**Comment by rbokel** [comment]
Ja, i think an error would be in order, or a strong warning at least, unless the test regexps are completely identical

**Comment by rbokel** [comment]
+1

**Pull request merged**
